Repository ess-dmsc/nexus-constructor, pull requests merged in 2019-12, with the labels that each got.

#522 430: Edit Pixel Data
  nexus_constructor/add_component_window.py
  nexus_constructor/component/component.py
  nexus_constructor/geometry/cylindrical_geometry.py
  nexus_constructor/geometry/off_geometry.py
  nexus_constructor/invalid_field_names.py
  nexus_constructor/nexus/nexus_wrapper.py
  nexus_constructor/pixel_data_to_nexus_utils.py
  nexus_constructor/pixel_mapping_widget.py
  nexus_constructor/pixel_options.py
  tests/test_component.py
  tests/test_pixel_data_to_nexus_utils.py
  tests/ui_tests/test_ui_add_component_window.py
  tests/ui_tests/test_ui_pixel_mapping_widget.py
  tests/ui_tests/test_ui_pixel_options_widget.py
  ui/add_component.py
Labels: Review In Progress

#588 574 allow specifying units for f142 stream
  .flake8
  nexus_constructor/component_fields.py
  nexus_constructor/stream_fields_widget.py
  tests/ui_tests/test_ui_fields.py
Labels: enhancement, high priority, tobias wish list

#590 re #565 fix h5py deprecation warning by specifying file modes
  nexus_constructor/component_fields.py
  nexus_constructor/nexus/nexus_wrapper.py
  nexus_constructor/stream_fields_widget.py
  tests/ui_tests/test_ui_add_component_window.py
Labels: warnings
