Repository ess-dmsc/nexus-constructor, pull requests merged in 2019-10, with the labels that each got.

#448 Fixing floating point array field UI issues
  nexus_constructor/array_dataset_table_widget.py
Labels: bug

#456 Squeeze arrays so 1-dimensional arrays are allowed to exist
  nexus_constructor/component_fields.py
Labels: bug

#475 sorting the nx_classes by name in the add component window
  nexus_constructor/add_component_window.py
Labels: enhancement

#450 Making the 3d view resizable
  nexus_constructor/main_window.py
  ui/main_window.py
  ui/main_window.ui
Labels: enhancement, low priority, question

#480 Adding simple UI tests for web view
  tests/ui_tests/test_ui_add_component_window.py
Labels: low priority

#482 Fix chopper shape not being shown
  nexus_constructor/component/chopper_shape.py
  nexus_constructor/geometry/disk_chopper/disk_chopper_checker.py
  tests/test_component_factory.py
  tests/test_disk_chopper_checker.py
Labels: bug

#464 460 optional filewriter fields
  nexus_constructor/filewriter_command_dialog.py
  nexus_constructor/json/filewriter_json_writer.py
  nexus_constructor/main_window.py
  nexus_constructor/validators.py
  tests/test_nexus_to_json.py
  tests/test_validators.py
  tests/ui_tests/test_ui_filewriter_command_options.py
Labels: enhancement

#493 477 - deleting transforms from chain when components are deleted
  nexus_constructor/component_tree_model.py
Labels: high priority, in progress

#501 Test and fix for reading vlen string datasets with NexusWrapper
  nexus_constructor/nexus/nexus_wrapper.py
  tests/test_nexus_wrapper.py
Labels: bug

#503 Make chopper component return NoShapeGeometry if cannot create m…
  nexus_constructor/component/chopper_shape.py
  tests/test_component_factory.py
Labels: bug, high priority

#491 481- fix stream and link writing
  nexus_constructor/component_fields.py
  nexus_constructor/json/filewriter_json_writer.py
  tests/test_json_writer.py
  tests/ui_tests/test_ui_add_component_window.py
Labels: bug, high priority

#506 Correctly dealing with 1D arrays in columnCount of array table widget
  nexus_constructor/array_dataset_table_widget.py
Labels: bug
