Repository ess-dmsc/nexus-constructor, pull requests merged in 2019-07, with the labels that each got.

#357 Adding dialog for when a nexus file has multiple entries
  nexus_constructor/main_window.py
  nexus_constructor/nexus/nexus_wrapper.py
  tests/test_instrument.py
  tests/test_nexus_wrapper.py
Labels: enhancement

#365 363: Gnomon is affected by aspect ratio of window
  nexus_constructor/instrument_view.py
  tests/test_instrument_view.py
Labels: dontmerge

#366 Fixing NXslit typo in components whitelist
  nexus_constructor/component_type.py
Labels: bug

#392 Allow spinboxes in cylinder editing section to take doubles/floats
  ui/add_component.py
  ui/add_component.ui
Labels: bug

#407 Replacing line edits with spin boxes for transformation frames
  nexus_constructor/transformation_view.py
  ui/transformation.py
  ui/transformation.ui
Labels: bug

#418 417: Fix String field issue
  nexus_constructor/component_fields.py
  tests/ui_tests/test_ui_add_component_window.py
Labels: bug, high priority
